--- 
trigger: 
  branches: 
    include: 
      - master
      - releases/*
      - develop
pr: 
  branches: 
    include: 
      - master
      - releases/*
      - develop
resources:
  repositories:
    - repository: pipeline
      type: git
      name: "Mobile API v1/ci-common-pipeline"
      
variables: 
  - template: variables.yml@pipeline
stages:
- template: build.yml@pipeline
  parameters:
    publish:   [
        { "branchName" :"refs/heads/develop", "env":"dev"},
        { "branchName" :"refs/heads/releases/v1", "env":"qa"}
     ]